name: Next.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # ✅ Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # ✅ Install deps using Bun
      - name: Install dependencies
        run: bun install

      # ✅ Lint
      - name: Run lint
        run: bun run lint

      # ✅ Build
      - name: Build project
        run: bun run build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-next-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-next-app:latest